# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7adb66518b1f53e15b624c3e9865f28df311a85ddf4d3b300bfc26f3cd6704e45e445e022b9c421f44cda701798e9d19228423b1c59fce37f0ab702193e52ec

test:
  secret_key_base: 4a745bb75881c9e4699a3166e48632ca2b4eb2812b46542dde8185e933fb7e1545079523cd77a6a83f42b6adc17eb63ac98a03056e70c5b3ddd73e10e7e8d9e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
